### ISSUE TITLE
Make 2FA only for superuser

### ISSUE THREAD

**Issue by vitalvas** [Elemnir/django-duo-auth#1]
I want to enable 2FA only for superusers.
In the code, I did not find any flags to do this.
Is it possible to implement it?

**Comment by Elemnir** [comment]
My intention was that if you only wanted to enable Duo for a subset of users, you would set up different Authentication Backends which would only authenticate for those users, and set them as the `FIRST_STAGE_BACKENDS` in your `DUO_CONFIG`. For instance, you could do something like: 

```
from django.contrib.auth.backends import ModelBackend

class SuperuserBackend(ModelBackend):
  def authenticate(self, request, username=None, password=None):
    if not is_superuser(username): 
      return None
    return super().authenticate(username=username, password=password)
```

And then set `AUTHENTICATION_BACKENDS = [SuperuserBackend, ModelBackend]`.
