### ISSUE TITLE
ModuleNotFoundError: No module named 'duo_auth'

### ISSUE THREAD

**Issue by heckyeahcool** [Elemnir/django-duo-auth#2]
Hi,
Not sure if I'm doing something wrong, but when I `pip install django-duo-auth`, everything seems fine, but there is no module in ../lib/python3.7/site-packages/.

Only ../lib/python3.7/site-packages/django_duo_auth-0.1.3.dist-info is installed. Any idea what I'm doing wrong?

Python --version 3.7.4
Django           2.2.6

**Comment by Elemnir** [comment]
I've not been able to replicate this issue using a local install of Python3.7.4 on a CentOS7.6 machine. Are you doing this inside of a virtual environment, or with the system-installed python? Could you please run the commands `which pip` and `pip --version` and provide the output?
