### ISSUE TITLE
Support for Duo Universal Prompt

### ISSUE THREAD

**Issue by jfsawin** [Elemnir/django-duo-auth#5]
Are there plans to add support for the new [Duo Universal Prompt](https://duo.com/docs/universal-prompt-update-guide)? The old style of prompt is not in immediate danger of deprecation, but it will be something this project will eventually have to implement to avoid becoming unusable in the future.

**Comment by Elemnir** [comment]
Unfortunately I haven't had time yet to cycle back around to this project since the Universal Prompt announcement, but eventually, yes, the plan is to support it along with the legacy prompt in future releases. Code submissions to help with getting this done sooner are welcome!

**Comment by Elemnir** [comment]
This has been addressed in the 1.0.0 release. The legacy prompt is indeed still supported at time of writing, so I've kept support for it within this project and documented how to access it if desired.
